/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryShoppingassistant.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryShoppingassistant (30 custom class methods, 20 custom properties)

#import "GTLQueryShoppingassistant.h"

#import "GTLShoppingassistantCheckIn.h"
#import "GTLShoppingassistantCheckInCollection.h"
#import "GTLShoppingassistantDeviceInfo.h"
#import "GTLShoppingassistantDeviceInfoCollection.h"
#import "GTLShoppingassistantGeoPt.h"
#import "GTLShoppingassistantKey.h"
#import "GTLShoppingassistantOffer.h"
#import "GTLShoppingassistantOfferCollection.h"
#import "GTLShoppingassistantPlace.h"
#import "GTLShoppingassistantPlaceInfoCollection.h"
#import "GTLShoppingassistantRecommendation.h"
#import "GTLShoppingassistantRecommendationCollection.h"

@implementation GTLQueryShoppingassistant

@dynamic address, checkinDate, count, descriptionProperty, deviceRegistrationID,
         distanceInKm, expiration, fields, identifier, imageUrl, key, latitude,
         location, longitude, name, offerID, placeID, placeId, title, userEmail;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

#pragma mark -
#pragma mark "checkInEndpoint" methods
// These create a GTLQueryShoppingassistant object.

+ (id)queryForCheckInEndpointGetWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.checkInEndpoint.get";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  query.expectedObjectClass = [GTLShoppingassistantCheckIn class];
  return query;
}

+ (id)queryForCheckInEndpointInsertWithObject:(GTLShoppingassistantCheckIn *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.checkInEndpoint.insert";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantCheckIn class];
  return query;
}

+ (id)queryForCheckInEndpointList {
  NSString *methodName = @"shoppingassistant.checkInEndpoint.list";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShoppingassistantCheckInCollection class];
  return query;
}

+ (id)queryForCheckInEndpointPatchWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.checkInEndpoint.patch";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  query.expectedObjectClass = [GTLShoppingassistantCheckIn class];
  return query;
}

+ (id)queryForCheckInEndpointRemoveWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.checkInEndpoint.remove";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  return query;
}

+ (id)queryForCheckInEndpointUpdateWithObject:(GTLShoppingassistantCheckIn *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.checkInEndpoint.update";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantCheckIn class];
  return query;
}

#pragma mark -
#pragma mark "deviceInfoEndpoint" methods
// These create a GTLQueryShoppingassistant object.

+ (id)queryForDeviceInfoEndpointGetWithIdentifier:(NSString *)identifier {
  NSString *methodName = @"shoppingassistant.deviceInfoEndpoint.get";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLShoppingassistantDeviceInfo class];
  return query;
}

+ (id)queryForDeviceInfoEndpointInsertWithObject:(GTLShoppingassistantDeviceInfo *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.deviceInfoEndpoint.insert";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantDeviceInfo class];
  return query;
}

+ (id)queryForDeviceInfoEndpointList {
  NSString *methodName = @"shoppingassistant.deviceInfoEndpoint.list";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLShoppingassistantDeviceInfoCollection class];
  return query;
}

+ (id)queryForDeviceInfoEndpointPatchWithIdentifier:(NSString *)identifier {
  NSString *methodName = @"shoppingassistant.deviceInfoEndpoint.patch";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLShoppingassistantDeviceInfo class];
  return query;
}

+ (id)queryForDeviceInfoEndpointRemoveWithIdentifier:(NSString *)identifier {
  NSString *methodName = @"shoppingassistant.deviceInfoEndpoint.remove";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (id)queryForDeviceInfoEndpointUpdateWithObject:(GTLShoppingassistantDeviceInfo *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.deviceInfoEndpoint.update";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantDeviceInfo class];
  return query;
}

#pragma mark -
#pragma mark "offerEndpoint" methods
// These create a GTLQueryShoppingassistant object.

+ (id)queryForOfferEndpointGetWithIdentifier:(NSString *)identifier {
  NSString *methodName = @"shoppingassistant.offerEndpoint.get";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLShoppingassistantOffer class];
  return query;
}

+ (id)queryForOfferEndpointInsertWithObject:(GTLShoppingassistantOffer *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.offerEndpoint.insert";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantOffer class];
  return query;
}

+ (id)queryForOfferEndpointListWithPlaceId:(NSString *)placeId {
  NSString *methodName = @"shoppingassistant.offerEndpoint.list";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.placeId = placeId;
  query.expectedObjectClass = [GTLShoppingassistantOfferCollection class];
  return query;
}

+ (id)queryForOfferEndpointPatchWithIdentifier:(NSString *)identifier {
  NSString *methodName = @"shoppingassistant.offerEndpoint.patch";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLShoppingassistantOffer class];
  return query;
}

+ (id)queryForOfferEndpointRemoveWithIdentifier:(NSString *)identifier {
  NSString *methodName = @"shoppingassistant.offerEndpoint.remove";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (id)queryForOfferEndpointUpdateWithObject:(GTLShoppingassistantOffer *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.offerEndpoint.update";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantOffer class];
  return query;
}

#pragma mark -
#pragma mark "placeEndpoint" methods
// These create a GTLQueryShoppingassistant object.

+ (id)queryForPlaceEndpointGetWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.placeEndpoint.get";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  query.expectedObjectClass = [GTLShoppingassistantPlace class];
  return query;
}

+ (id)queryForPlaceEndpointInsertWithObject:(GTLShoppingassistantPlace *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.placeEndpoint.insert";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantPlace class];
  return query;
}

+ (id)queryForPlaceEndpointListWithCount:(NSInteger)count
                            distanceInKm:(long long)distanceInKm
                                latitude:(NSString *)latitude
                               longitude:(NSString *)longitude {
  NSString *methodName = @"shoppingassistant.placeEndpoint.list";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.count = count;
  query.distanceInKm = distanceInKm;
  query.latitude = latitude;
  query.longitude = longitude;
  query.expectedObjectClass = [GTLShoppingassistantPlaceInfoCollection class];
  return query;
}

+ (id)queryForPlaceEndpointPatchWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.placeEndpoint.patch";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  query.expectedObjectClass = [GTLShoppingassistantPlace class];
  return query;
}

+ (id)queryForPlaceEndpointRemoveWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.placeEndpoint.remove";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  return query;
}

+ (id)queryForPlaceEndpointUpdateWithObject:(GTLShoppingassistantPlace *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.placeEndpoint.update";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantPlace class];
  return query;
}

#pragma mark -
#pragma mark "recommendationEndpoint" methods
// These create a GTLQueryShoppingassistant object.

+ (id)queryForRecommendationEndpointGetWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.recommendationEndpoint.get";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  query.expectedObjectClass = [GTLShoppingassistantRecommendation class];
  return query;
}

+ (id)queryForRecommendationEndpointInsertWithObject:(GTLShoppingassistantRecommendation *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.recommendationEndpoint.insert";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantRecommendation class];
  return query;
}

+ (id)queryForRecommendationEndpointListWithPlaceId:(NSString *)placeId {
  NSString *methodName = @"shoppingassistant.recommendationEndpoint.list";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.placeId = placeId;
  query.expectedObjectClass = [GTLShoppingassistantRecommendationCollection class];
  return query;
}

+ (id)queryForRecommendationEndpointPatchWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.recommendationEndpoint.patch";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  query.expectedObjectClass = [GTLShoppingassistantRecommendation class];
  return query;
}

+ (id)queryForRecommendationEndpointRemoveWithIdentifier:(long long)identifier {
  NSString *methodName = @"shoppingassistant.recommendationEndpoint.remove";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.identifier = [NSNumber numberWithLongLong:identifier];
  return query;
}

+ (id)queryForRecommendationEndpointUpdateWithObject:(GTLShoppingassistantRecommendation *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"shoppingassistant.recommendationEndpoint.update";
  GTLQueryShoppingassistant *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLShoppingassistantRecommendation class];
  return query;
}

@end
