/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLQueryShoppingassistant.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryShoppingassistant (30 custom class methods, 20 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLShoppingassistantCheckIn;
@class GTLShoppingassistantDeviceInfo;
@class GTLShoppingassistantGeoPt;
@class GTLShoppingassistantKey;
@class GTLShoppingassistantOffer;
@class GTLShoppingassistantPlace;
@class GTLShoppingassistantRecommendation;

@interface GTLQueryShoppingassistant : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *address;
@property (retain) GTLDateTime *checkinDate;
@property (assign) NSInteger count;
// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;
@property (copy) NSString *deviceRegistrationID;
@property (assign) long long distanceInKm;
@property (retain) GTLDateTime *expiration;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
// "identifier" has different types for some query methods; see the
// documentation for the right type for each query method.
@property (retain) id identifier;
@property (copy) NSString *imageUrl;
@property (retain) GTLShoppingassistantKey *key;
@property (copy) NSString *latitude;
@property (retain) GTLShoppingassistantGeoPt *location;
@property (copy) NSString *longitude;
@property (copy) NSString *name;
@property (copy) NSString *offerID;
@property (copy) NSString *placeID;
@property (copy) NSString *placeId;
@property (copy) NSString *title;
@property (copy) NSString *userEmail;

#pragma mark -
#pragma mark "checkInEndpoint" methods
// These create a GTLQueryShoppingassistant object.

// Method: shoppingassistant.checkInEndpoint.get
// Fetches a GTLShoppingassistantCheckIn.
+ (id)queryForCheckInEndpointGetWithIdentifier:(long long)identifier;

// Method: shoppingassistant.checkInEndpoint.insert
// Fetches a GTLShoppingassistantCheckIn.
+ (id)queryForCheckInEndpointInsertWithObject:(GTLShoppingassistantCheckIn *)object;

// Method: shoppingassistant.checkInEndpoint.list
// Fetches a GTLShoppingassistantCheckInCollection.
+ (id)queryForCheckInEndpointList;

// Method: shoppingassistant.checkInEndpoint.patch
//  Optional:
//   checkinDate: GTLDateTime
//   key: GTLShoppingassistantKey
//   placeId: NSString
//   userEmail: NSString
// Fetches a GTLShoppingassistantCheckIn.
+ (id)queryForCheckInEndpointPatchWithIdentifier:(long long)identifier;

// Method: shoppingassistant.checkInEndpoint.remove
+ (id)queryForCheckInEndpointRemoveWithIdentifier:(long long)identifier;

// Method: shoppingassistant.checkInEndpoint.update
// Fetches a GTLShoppingassistantCheckIn.
+ (id)queryForCheckInEndpointUpdateWithObject:(GTLShoppingassistantCheckIn *)object;

#pragma mark -
#pragma mark "deviceInfoEndpoint" methods
// These create a GTLQueryShoppingassistant object.

// Method: shoppingassistant.deviceInfoEndpoint.get
// Fetches a GTLShoppingassistantDeviceInfo.
+ (id)queryForDeviceInfoEndpointGetWithIdentifier:(NSString *)identifier;

// Method: shoppingassistant.deviceInfoEndpoint.insert
// Fetches a GTLShoppingassistantDeviceInfo.
+ (id)queryForDeviceInfoEndpointInsertWithObject:(GTLShoppingassistantDeviceInfo *)object;

// Method: shoppingassistant.deviceInfoEndpoint.list
// Fetches a GTLShoppingassistantDeviceInfoCollection.
+ (id)queryForDeviceInfoEndpointList;

// Method: shoppingassistant.deviceInfoEndpoint.patch
//  Optional:
//   deviceRegistrationID: NSString
// Fetches a GTLShoppingassistantDeviceInfo.
+ (id)queryForDeviceInfoEndpointPatchWithIdentifier:(NSString *)identifier;

// Method: shoppingassistant.deviceInfoEndpoint.remove
+ (id)queryForDeviceInfoEndpointRemoveWithIdentifier:(NSString *)identifier;

// Method: shoppingassistant.deviceInfoEndpoint.update
// Fetches a GTLShoppingassistantDeviceInfo.
+ (id)queryForDeviceInfoEndpointUpdateWithObject:(GTLShoppingassistantDeviceInfo *)object;

#pragma mark -
#pragma mark "offerEndpoint" methods
// These create a GTLQueryShoppingassistant object.

// Method: shoppingassistant.offerEndpoint.get
// Fetches a GTLShoppingassistantOffer.
+ (id)queryForOfferEndpointGetWithIdentifier:(NSString *)identifier;

// Method: shoppingassistant.offerEndpoint.insert
// Fetches a GTLShoppingassistantOffer.
+ (id)queryForOfferEndpointInsertWithObject:(GTLShoppingassistantOffer *)object;

// Method: shoppingassistant.offerEndpoint.list
// Fetches a GTLShoppingassistantOfferCollection.
+ (id)queryForOfferEndpointListWithPlaceId:(NSString *)placeId;

// Method: shoppingassistant.offerEndpoint.patch
//  Optional:
//   descriptionProperty: NSString
//   imageUrl: NSString
//   offerID: NSString
//   title: NSString
// Fetches a GTLShoppingassistantOffer.
+ (id)queryForOfferEndpointPatchWithIdentifier:(NSString *)identifier;

// Method: shoppingassistant.offerEndpoint.remove
+ (id)queryForOfferEndpointRemoveWithIdentifier:(NSString *)identifier;

// Method: shoppingassistant.offerEndpoint.update
// Fetches a GTLShoppingassistantOffer.
+ (id)queryForOfferEndpointUpdateWithObject:(GTLShoppingassistantOffer *)object;

#pragma mark -
#pragma mark "placeEndpoint" methods
// These create a GTLQueryShoppingassistant object.

// Method: shoppingassistant.placeEndpoint.get
// Fetches a GTLShoppingassistantPlace.
+ (id)queryForPlaceEndpointGetWithIdentifier:(long long)identifier;

// Method: shoppingassistant.placeEndpoint.insert
// Fetches a GTLShoppingassistantPlace.
+ (id)queryForPlaceEndpointInsertWithObject:(GTLShoppingassistantPlace *)object;

// Method: shoppingassistant.placeEndpoint.list
// Fetches a GTLShoppingassistantPlaceInfoCollection.
+ (id)queryForPlaceEndpointListWithCount:(NSInteger)count
                            distanceInKm:(long long)distanceInKm
                                latitude:(NSString *)latitude
                               longitude:(NSString *)longitude;

// Method: shoppingassistant.placeEndpoint.patch
//  Optional:
//   address: NSString
//   key: GTLShoppingassistantKey
//   location: GTLShoppingassistantGeoPt
//   name: NSString
//   placeId: NSString
//   placeID: NSString
// Fetches a GTLShoppingassistantPlace.
+ (id)queryForPlaceEndpointPatchWithIdentifier:(long long)identifier;

// Method: shoppingassistant.placeEndpoint.remove
+ (id)queryForPlaceEndpointRemoveWithIdentifier:(long long)identifier;

// Method: shoppingassistant.placeEndpoint.update
// Fetches a GTLShoppingassistantPlace.
+ (id)queryForPlaceEndpointUpdateWithObject:(GTLShoppingassistantPlace *)object;

#pragma mark -
#pragma mark "recommendationEndpoint" methods
// These create a GTLQueryShoppingassistant object.

// Method: shoppingassistant.recommendationEndpoint.get
// Fetches a GTLShoppingassistantRecommendation.
+ (id)queryForRecommendationEndpointGetWithIdentifier:(long long)identifier;

// Method: shoppingassistant.recommendationEndpoint.insert
// Fetches a GTLShoppingassistantRecommendation.
+ (id)queryForRecommendationEndpointInsertWithObject:(GTLShoppingassistantRecommendation *)object;

// Method: shoppingassistant.recommendationEndpoint.list
// Fetches a GTLShoppingassistantRecommendationCollection.
+ (id)queryForRecommendationEndpointListWithPlaceId:(NSString *)placeId;

// Method: shoppingassistant.recommendationEndpoint.patch
//  Optional:
//   descriptionProperty: NSString
//   expiration: GTLDateTime
//   imageUrl: NSString
//   title: NSString
// Fetches a GTLShoppingassistantRecommendation.
+ (id)queryForRecommendationEndpointPatchWithIdentifier:(long long)identifier;

// Method: shoppingassistant.recommendationEndpoint.remove
+ (id)queryForRecommendationEndpointRemoveWithIdentifier:(long long)identifier;

// Method: shoppingassistant.recommendationEndpoint.update
// Fetches a GTLShoppingassistantRecommendation.
+ (id)queryForRecommendationEndpointUpdateWithObject:(GTLShoppingassistantRecommendation *)object;

@end
