/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantCheckIn.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantCheckIn (0 custom class methods, 4 custom properties)

#import "GTLShoppingassistantCheckIn.h"

#import "GTLShoppingassistantKey.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantCheckIn
//

@implementation GTLShoppingassistantCheckIn
@dynamic checkinDate, key, placeId, userEmail;
@end
