/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantRecommendation.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantRecommendation (0 custom class methods, 4 custom properties)

#import "GTLShoppingassistantRecommendation.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantRecommendation
//

@implementation GTLShoppingassistantRecommendation
@dynamic descriptionProperty, expiration, imageUrl, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"description"
                                forKey:@"descriptionProperty"];
  return map;
}

@end
