/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantCheckIn.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantCheckIn (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLShoppingassistantKey;

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantCheckIn
//

@interface GTLShoppingassistantCheckIn : GTLObject
@property (retain) GTLDateTime *checkinDate;
@property (retain) GTLShoppingassistantKey *key;
@property (copy) NSString *placeId;
@property (copy) NSString *userEmail;
@end
