/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantOfferCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantOfferCollection (0 custom class methods, 1 custom properties)

#import "GTLShoppingassistantOfferCollection.h"

#import "GTLShoppingassistantOffer.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantOfferCollection
//

@implementation GTLShoppingassistantOfferCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingassistantOffer class]
                                forKey:@"items"];
  return map;
}

@end
