/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantDeviceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantDeviceInfo (0 custom class methods, 1 custom properties)

#import "GTLShoppingassistantDeviceInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantDeviceInfo
//

@implementation GTLShoppingassistantDeviceInfo
@dynamic deviceRegistrationID;
@end
