/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantDeviceInfoCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantDeviceInfoCollection (0 custom class methods, 1 custom properties)

#import "GTLShoppingassistantDeviceInfoCollection.h"

#import "GTLShoppingassistantDeviceInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantDeviceInfoCollection
//

@implementation GTLShoppingassistantDeviceInfoCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingassistantDeviceInfo class]
                                forKey:@"items"];
  return map;
}

@end
