/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantOffer.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantOffer (0 custom class methods, 4 custom properties)

#import "GTLShoppingassistantOffer.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantOffer
//

@implementation GTLShoppingassistantOffer
@dynamic descriptionProperty, imageUrl, offerID, title;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"description"
                                forKey:@"descriptionProperty"];
  return map;
}

@end
