/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantPlace.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantPlace (0 custom class methods, 6 custom properties)

#import "GTLShoppingassistantPlace.h"

#import "GTLShoppingassistantGeoPt.h"
#import "GTLShoppingassistantKey.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantPlace
//

@implementation GTLShoppingassistantPlace
@dynamic address, key, location, name, placeId, placeID;
@end
