/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantPlaceInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantPlaceInfo (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLShoppingassistantGeoPt;
@class GTLShoppingassistantKey;

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantPlaceInfo
//

@interface GTLShoppingassistantPlaceInfo : GTLObject
@property (copy) NSString *address;
@property (retain) NSNumber *distanceInKilometers;  // doubleValue
@property (retain) GTLShoppingassistantKey *key;
@property (retain) GTLShoppingassistantGeoPt *location;
@property (copy) NSString *name;
@property (copy) NSString *placeId;
@property (copy) NSString *placeID;
@end
