/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantPlace.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantPlace (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLShoppingassistantGeoPt;
@class GTLShoppingassistantKey;

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantPlace
//

@interface GTLShoppingassistantPlace : GTLObject
@property (copy) NSString *address;
@property (retain) GTLShoppingassistantKey *key;
@property (retain) GTLShoppingassistantGeoPt *location;
@property (copy) NSString *name;
@property (copy) NSString *placeId;
@property (copy) NSString *placeID;
@end
