/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantPlaceInfoCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantPlaceInfoCollection (0 custom class methods, 1 custom properties)

#import "GTLShoppingassistantPlaceInfoCollection.h"

#import "GTLShoppingassistantPlaceInfo.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantPlaceInfoCollection
//

@implementation GTLShoppingassistantPlaceInfoCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLShoppingassistantPlaceInfo class]
                                forKey:@"items"];
  return map;
}

@end
