/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistant.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API

#import "GTLShoppingassistantCheckIn.h"
#import "GTLShoppingassistantCheckInCollection.h"
#import "GTLShoppingassistantDeviceInfo.h"
#import "GTLShoppingassistantDeviceInfoCollection.h"
#import "GTLShoppingassistantGeoPt.h"
#import "GTLShoppingassistantKey.h"
#import "GTLShoppingassistantOffer.h"
#import "GTLShoppingassistantOfferCollection.h"
#import "GTLShoppingassistantPlace.h"
#import "GTLShoppingassistantPlaceInfo.h"
#import "GTLShoppingassistantPlaceInfoCollection.h"
#import "GTLShoppingassistantRecommendation.h"
#import "GTLShoppingassistantRecommendationCollection.h"

#import "GTLQueryShoppingassistant.h"
#import "GTLServiceShoppingassistant.h"
