/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantGeoPt.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantGeoPt (0 custom class methods, 2 custom properties)

#import "GTLShoppingassistantGeoPt.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantGeoPt
//

@implementation GTLShoppingassistantGeoPt
@dynamic latitude, longitude;
@end
