/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2013 Google Inc.
 */

//
//  GTLShoppingassistantPlaceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   shoppingassistant/v1
// Description:
//   This is an API
// Classes:
//   GTLShoppingassistantPlaceInfo (0 custom class methods, 7 custom properties)

#import "GTLShoppingassistantPlaceInfo.h"

#import "GTLShoppingassistantGeoPt.h"
#import "GTLShoppingassistantKey.h"

// ----------------------------------------------------------------------------
//
//   GTLShoppingassistantPlaceInfo
//

@implementation GTLShoppingassistantPlaceInfo
@dynamic address, distanceInKilometers, key, location, name, placeId, placeID;
@end
